### ISSUE TITLE
Call Methods with or without ()?

### ISSUE THREAD

**Issue by tanthammar** [tanthammar/VueNewbieQuestions#1]
## Varför *måste* man referera till methods med parentes() och ibland utan?
Återigen någon baskunskap som jag missat...

#### Beskrivning

* Jag har ett formulär, som skapar ett projekt, **@submit**
* Har en **method: refreshProjects()** som gör ett ajax anrop och hämtar några projects
* On **mounted()** så använder jag **refreshProjects()** för att *populera* **data: projects[]**
* **@submit** så använder jag återigen **refreshProjects()** för att *uppdatera* **data: projects[]**
* (Ignorera ifall detta är rätt eller fel sätt att uppdatera listan med projekt, det är bara ett exempel för mig att leka med ajax requests och för att förstå skillnaden med parenteser() )

---
# Exempel 1, måste använda parentes()

#### Rätt - Gör jag så här så *populeras* data korrekt:
```js
mounted() {
    this.refreshProjects();
  },
```

#### Fel - Gör jag så här så händer ingenting:
```js
mounted() {
    this.refreshProjects;
  },
```

---
# Exempel 2, funkar *inte* med parentes()

#### Rätt – Gör jag så här så *uppdateras* data korrekt:
```js
methods: {
    onSubmit() {
      axios.post('/projects', this.$data)
        .then(this.refreshProjects)
      .catch(error => this.errors.record(error.response.data));
},
```

#### Fel – Gör jag så här, så måte jag posta 2ggr!! (varför då?) för att **uppdatera** data:
1. När sidan laddas första gången så behöver jag posta formuläret 2 ggr för att listan med projekt skall uppdateras på sidan.
    1. Första submit/klick händer inget i "view", kollar även data i vue developer tools. (Då klickar man givetvis en gång till, vilket skapar två projekt med samma namn)
    1. Andra submit så visas projektet som skapades i steg 1
    1. Tredje submit så visas projektet från steg 2, så sidan ligger liksom ett steg efter
    1. Om jag laddar om sidan då visas de två projekten som skapades vid steg 1 

```js
methods: {
    onSubmit() {
      axios.post('/projects', this.$data)
        .then(this.refreshProjects())
      .catch(error => this.errors.record(error.response.data));
},
```
---
# Summering

Varför måste jag använda parentes ibland, och ibland inte? 
Hur skall jag veta när det behövs eller ej.

**Vad händer i exempel två?**

Varför funkar det *inte* på första submit, men bestämmer sig för att funka på andra?
Och ändå uppdateras inte projektlistan korrekt när refreshProjects() körs @submit.

---
#### All kod

```js
var app = new Vue({
  el: '#app',

  data: {
    name: '',
    description: '',
    errors: new Errors(),
    projects: []
  },

  mounted() {
    this.refreshProjects();
  },

  methods: {
    onSubmit() {
      axios.post('/projects', this.$data)
        .then(this.refreshProjects)
        .catch(error => this.errors.record(error.response.data));
    },

    refreshProjects() {
      axios.get('/projects/five')
        .then(
          response => this.projects = response.data.projects
        );
    }
  }

})
```

```html
<div class="card my-5">
    <div class="card-header">
        The 5 latest projects
    </div>
    <ul class="list-group list-group-flush">
        <template v-if="projects.length">
            <li v-for="project in projects" :key="project.id" v-text="project.name" class="list-group-item"></li>
        </template>
        <li v-else class="list-group-item">No projects created yet</li>
    </ul>
</div>


<div class="card">
    <div class="card-header">
        Add Project
    </div>
    <div class="card-body">
        <form method="POST" action="/projects" @submit.prevent="onSubmit">
            @csrf
            <div class="form-group">
                <label for="name">Project Name</label>
                <input v-model="name" type="text" class="form-control" id="name" name="name"
                    placeholder="Enter project name">
                <small class="text-danger" v-text="errors.get('name')"></small>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea v-model="description" rows="8" class="form-control" class="form-control" id="description"
                    name="description" placeholder="Description"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
```
![parenteser](https://user-images.githubusercontent.com/21239634/54475901-3e589e00-47f7-11e9-8f5e-8ad0becc135c.png)

**Comment by iaK** [comment]
Det funkar precis som i php faktikst, men det används lite mer i javascript-världen.

När du inte skriver några parenteser, du referrerar du bara funktionen, den körs inte.

så.. 

```javascript

    let test = function () {
        console.log("test");
    }

    test;  // händer liksom ingenting, som att skriva

    let a = "a";

    a; 

```

Så om du bara skriver funktionsnamnet utan parentes händer ingenting,
MEN, det hela blir lite mer användbart om du t.ex använder det som en parameter till en annan funktion, som en callback. Du skickar då en referens till funktionen, utan att anropa den. Funktionen du skickar din callback till kan då göra vad den vill med funktionen, köra den med de parametrar den vill osv.

Dumt exempel, men som kanske får det att klarna :)

```javascript
    
    let addOneToResult = function (callback) {
        let result = callback(5, 5);

        return result + 1;
    }

    let addNumbers = function (first, second) {
        return first + second;
    }

    addOneToResult(addNumbers); // 11

```

Skriver du däremot MED parenteser, så skickar du resultat av den första funktionen in till den andra

```javascript
    
    let addOne = function (number) {
        return number + 1;
    }

    let addTwo = function (number) {
        return number + 2;
    }

    addTwo(addOne(1)) // 4

```

En funktion kan också returera en ny funktion. Då kan du "chaina" funktions-anrop.

Hoppas det förklarar Exempel 1.

I exempel 2 händer det lite spännande saker.

Om du i (som i första kodsnutten) skickar med en referens till funktionen du vill köra, så kommer den köras EFTER ajax-anropet är klart. Skickar du skriver med parentes, och alltså kör funktionen och returerar resultatet istället för en referens, så kommer refreshProjects köras FÖRE ajax-anropet är klart, och därmed kommer inte servern ha hunnit uppdatera datan (vilket jag antar att du gör i det första post-anropet).

Hoppas jag lyckades förklara detta på ett förståerligt sätt. Hojta till om något är oklart. Blir lätt lite rörigt :)

**Comment by Krisell** [comment]
@iaK skrev det utförligt och bra. Tänkte fylla på lite:

Om vi har en funktion
```js
function add (numberOne, numberTwo) {
  return numberOne + numberTwo
}
```

så är `add` därefter den variabel som pekar på funktionen, `typeof add === 'function'`. Parenteser används för att "köra" funktionen, direkt.

Argumentet som skickas till `then()` ska vara en funktion, den som körs när anropet "kommer tillbaka". `add` är en funktion, `add()` är inte en funktion (den returnerar ett tal).

Inget av detta är specifikt för Vue utan ren JavaScript. Däremot tror jag att det finns en risk att Vue-syntaxen kan vara lite förvirrande relaterat till detta. I Vue ger `@click="fn"` och `@click="fn()"` samma effekt. Vue plockar helt enkelt pekaren till funktionen oavsett parenteser. Detta går eftersom Vue-kod i HTML initialt är strängar, inte JS som körs direkt.

Jag skriver i regel såhär, även om det är onödigt, kanske för att minska risken att skriva fel (slippa "komma ihåg" om det ska vara parentes eller inte):
```js
.then(() => this.refreshProjects())
```

**Comment by tanthammar** [comment]
Nu förstår jag och diffusa minnen pockar på uppmärksamhet. 
Glömmer av att det är javascript och blir förblindad av att det är ett "nytt" språk jag försöker förstå.
Ramlade i fällan med `@click="fn"` och `@click="fn()"` och blev väldigt förvirrad när båda fungerade.

Det här klarar jag att memorera:

- med parentes, körs funktionen direkt, returnerar ett värde. tex mounted() { this.someFunction(); }
- utan parentes, kan den användas som ett argument till en annan funktion, tex .then(someFunction)

Det här gör mig yr - ha ha
- man kan definiera en funktion som returnerar en funktion, eller skapa chainable functions

Stort tack till er båda, för ert tålamod och hjälpsamhet!
